# REST API Application generated by DevHive AI
from fastapi import FastAPI, HTTPException
from models import ItemModel
from service import CoreService

app = FastAPI(title="Generated Service", version="1.0.0")
service = CoreService()

@app.get("/")
def health_check():
    return {"status": "online", "engine": "DevHive AI"}

@app.get("/items")
def list_items():
    return service.get_all()

@app.post("/items")
def add_item(item: ItemModel):
    return service.create(item)
