# Core Business Logic generated by DevHive AI
from typing import List, Optional
from models import ItemModel

class CoreService:
    def __init__(self):
        self._items = []
        self._counter = 1

    def create(self, item: ItemModel) -> ItemModel:
        item.id = self._counter
        self._counter += 1
        self._items.append(item)
        return item

    def get_all(self) -> List[ItemModel]:
        return self._items
